kafka.bootstrap-servers=localhost:9092
kafka.topic.user-actions=stats.user-actions.v1
kafka.topic.events-similarity=stats.events-similarity.v1
kafka.consumer.client-id=aggregator-user-actions-consumer
kafka.consumer.group-id=aggregator-user-actions
kafka.consumer.poll-timeout-ms=1000
kafka.producer.send-timeout-ms=5000

eureka.instance.instance-id=${spring.application.name}:${random.uuid}
