grpc.server.port=0

spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5432/analyzer
spring.datasource.username=dbuser
spring.datasource.password=12345
spring.sql.init.mode=always

kafka.bootstrap-servers=localhost:9092
kafka.topic.user-actions=stats.user-actions.v1
kafka.topic.events-similarity=stats.events-similarity.v1
kafka.consumer.poll-timeout-ms=500
kafka.consumer.user-actions.client-id=analyzer-user-actions-consumer
kafka.consumer.user-actions.group-id=analyzer-user-actions
kafka.consumer.event-similarities.client-id=analyzer-event-similarities-consumer
kafka.consumer.event-similarities.group-id=analyzer-event-similarities

eureka.instance.instance-id=${spring.application.name}:${random.uuid}
