CREATE TABLE IF NOT EXISTS participation_requests (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    event_id     BIGINT                      NOT NULL,
    requester_id BIGINT                      NOT NULL,
    status       VARCHAR(20)                 NOT NULL DEFAULT 'PENDING',
    created      TIMESTAMP WITHOUT TIME ZONE NOT NULL,

    CONSTRAINT pk_participation_requests PRIMARY KEY (id),
    CONSTRAINT uq_request_per_event UNIQUE (event_id, requester_id)
);
