grpc.server.port=0

kafka.bootstrap-servers=localhost:9092
kafka.topic.user-actions=stats.user-actions.v1
kafka.producer.send-timeout-ms=5000

eureka.instance.instance-id=${spring.application.name}:${random.uuid}
