server.port=8080

spring.cloud.gateway.discovery.locator.enabled=false

spring.cloud.gateway.routes[0].id=main-service-api-compilations
spring.cloud.gateway.routes[0].uri=lb://ewm-main-service
spring.cloud.gateway.routes[0].predicates[0]=Path=/compilations,/compilations/*

spring.cloud.gateway.routes[1].id=main-service-api-admin-categories
spring.cloud.gateway.routes[1].uri=lb://ewm-main-service
spring.cloud.gateway.routes[1].predicates[0]=Path=/admin/categories,/admin/categories/*

spring.cloud.gateway.routes[2].id=main-service-api-users-events
spring.cloud.gateway.routes[2].uri=lb://ewm-main-service
spring.cloud.gateway.routes[2].predicates[0]=Path=/users/*/events,/users/*/events/**

spring.cloud.gateway.routes[3].id=main-service-api-public-categories
spring.cloud.gateway.routes[3].uri=lb://ewm-main-service
spring.cloud.gateway.routes[3].predicates[0]=Path=/categories,/categories/*

spring.cloud.gateway.routes[4].id=main-service-api-admin-events
spring.cloud.gateway.routes[4].uri=lb://ewm-main-service
spring.cloud.gateway.routes[4].predicates[0]=Path=/admin/events,/admin/events/**

spring.cloud.gateway.routes[5].id=main-service-api-public-events
spring.cloud.gateway.routes[5].uri=lb://ewm-main-service
spring.cloud.gateway.routes[5].predicates[0]=Path=/events,/events/*

spring.cloud.gateway.routes[6].id=main-service-api-users-requests
spring.cloud.gateway.routes[6].uri=lb://ewm-main-service
spring.cloud.gateway.routes[6].predicates[0]=Path=/users/*/requests,/users/*/requests/**

spring.cloud.gateway.routes[7].id=main-service-api-admin-users
spring.cloud.gateway.routes[7].uri=lb://ewm-main-service
spring.cloud.gateway.routes[7].predicates[0]=Path=/admin/users,/admin/users/*

spring.cloud.gateway.routes[8].id=main-service-api-admin-compilations
spring.cloud.gateway.routes[8].uri=lb://ewm-main-service
spring.cloud.gateway.routes[8].predicates[0]=Path=/admin/compilations,/admin/compilations/*

spring.cloud.gateway.routes[9].id=main-service-api-public-places
spring.cloud.gateway.routes[9].uri=lb://ewm-main-service
spring.cloud.gateway.routes[9].predicates[0]=Path=/places,/places/*

spring.cloud.gateway.routes[10].id=main-service-api-admin-places
spring.cloud.gateway.routes[10].uri=lb://ewm-main-service
spring.cloud.gateway.routes[10].predicates[0]=Path=/admin/places,/admin/places/*